name: Deploy gh-pages

on:
  push:
    branches: [final-main]

permissions:
  contents: write    # precisa disto para fazer push na gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: 'npm'

    - run: npm ci

    - name: Generate environment.ts
      run: |
        mkdir -p src/environments
        cat > src/environments/environment.ts << EOF
        export const environment = {
          production: true,
          supabaseUrl: "${{ secrets.SUPABASE_URL }}",
          supabaseKey: "${{ secrets.SUPABASE_ANON_KEY }}"
        };
        EOF

    - run: npm run build -- --configuration production

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/readrometer
