name: Deploy Angular to GitHub Pages
on:
  push:
    branches: [ "feature/deploy" ]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: |
          mkdir -p src/environments
          echo "export const environment = { production: true, supabaseUrl: '${SUPABASE_URL}', supabaseKey: '${SUPABASE_KEY}' };" > src/environments/environment.ts
      - run: npm run build -- --base-href=/Projeto-Final-Readrometer/
      - run: |
          cd docs
          cp index.html 404.html
          touch .nojekyll
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          user: joanacf1005
          repo: Projeto-Final-Readrometer

