name: Deploy GitHub Pages
on:
  push:
    branches: [ final-main ]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    if: github.ref == 'refs/heads/final-main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24  
        cache: 'npm'     
    
    - name: Instalar dependências
      run: npm ci
    
    - name: Generate environment.ts  
      run: |
        mkdir -p src/environments
        cat > src/environments/environment.development.ts << EOF
        export const environment = {
          production: false,
          supabaseUrl: "${{ secrets.SUPABASE_URL }}",
          supabaseKey: "${{ secrets.SUPABASE_ANON_KEY }}"
        };
        EOF
    
    - name: Build
      run: npm run build
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'dist/readrometer'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
